apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.extraInitContainers }}
      {{- toYaml .Values.extraInitContainers |  nindent 6 }}
      {{- end }}
      containers:
      {{- if .Values.sideCars }}
      {{- toYaml .Values.sideCars |  nindent 6 }}
      {{- end }}
      - name:  {{ .Values.appName }}
        env:
        {{- include "omar-twofishes.envVars" . | nindent 8 }}
        image: "{{ .Values.global.dockerRepository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          httpGet:
            path: /health
            port: 8082
            scheme: HTTP
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 15
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 3
          httpGet:
            port: 8082
            path: /
        ports:
        - containerPort: {{ .Values.internalPort }}
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
        - containerPort: 8083
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      {{- if .Values.global.useImagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.appName }}-pull-secret
      {{- end }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
