apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: {{ .Values.appName }}-app
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: 8082-tcp
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: 8083-tcp
    port: 8083
    protocol: TCP
    targetPort: 8083
  sessionAffinity: None
  type: ClusterIP
